spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli_college?&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
canal:
  hostname: 192.168.254.129
  port: 11111